import Head from "next/head";
import Hero from "../components/Hero/Hero";
import Story from "../components/OurStory/Story";
import Reviews from "../components/Reviews/Reviews";
import styles from "../styles/Home.module.scss";
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Red Lips</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero styles={styles} />
      <Story styles={styles} />
      <Reviews styles={styles} />
    </div>
  );
}
